seed: 2025
data_name: movielens-1m
data_dir: datasets
use_pretrain: 0
pretrain_embedding_dir: ''
save_dir: trained_model/MCRec/movielens-1m
eval_user_limit: 1000
use_gpu: 1
embed_dim: 64
mlp_layers: [512, 256, 128, 64]
lr: 0.001
batch_size: 256
num_neg: 4
n_epoch: 10
evaluate_every: 1
Ks: [10]
umtm_path_num: 3
umum_path_num: 2
umtmum_path_num: 2
uuum_path_num: 1
umtm_timestamp: 10
umum_timestamp: 8
umtmum_timestamp: 6
uuum_timestamp: 5
mcrec_feature_size: 64
cf_batch_size: 256
test_batch_size: 1000
cf_print_every: 100
stopping_steps: 5
